use std::ops::Deref;
use crate::location::ResourceLocation;
use crate::registry::{IndexedRegistry, Registry};
use crate::resource::{IndexedResource, Resource};

/// Represents a reference to an asset provided by a datapack. This may either be a reference to
/// a builtin (vanilla) asset or a reference to an external asset loaded from a datapack.
///
/// As a note, all assets must be grabbed through this struct. Generated assets are baked into the
/// binary but are not accessible to be used directly. There will be some [StaticResource] constants
/// that are autogenerated by this crate, but those must be loaded via [StaticResource::load] or
/// by using the [From<StaticResource>] implementation for this struct.
///
/// In most cases, you will want to use the [Registry::iter_assets] method to get an iterator over
/// all assets loaded into that registry.
pub struct ResourceHolder<T: Resource> {
    pub(crate) location: ResourceLocation<'static, T>,
    pub(crate) reference: &'static T,
}

impl<T: Resource> ResourceHolder<T> {
    /// Attempts to grab a new ResourceHolder from the central resource manager.
    ///
    /// # Arguments
    ///  * `namespace`: the namespace that the resource is located in.
    ///  * `path`: the path that the resource is located at.
    ///
    /// # Returns
    ///  * `Some(self)`: the resource was successfully fetched.
    ///  * `None`: the resource could not be found.
    pub fn new(namespace: impl Into<String>, path: impl Into<String>) -> Option<Self> {
        let location = ResourceLocation::<T>::new(namespace, path);
        let reference = T::registry().try_get(&location)?;

        Some(Self {
            location,
            reference,
        })
    }

    /// Attempts to grab a new ResourceHolder from the central resource manager at the default
    /// namespace.
    ///
    /// # Arguments
    ///  * `path`: the path that the resource is located at within the default namespace.
    ///
    /// # Returns
    ///  * `Some(self)`: the resource was successfully fetched.
    ///  * `None`: the resource could not be found.
    pub fn with_default_namespace(path: impl Into<String>) -> Option<Self> {
        let location = ResourceLocation::<T>::with_default_namespace(path);
        let reference = T::registry().try_get(&location)?;

        Some(Self {
            location,
            reference,
        })
    }

    /// Returns the [ResourceLocation] that this holder contains the resource for.
    pub fn location(&self) -> &ResourceLocation<'static, T> {
        &self.location
    }
}

impl<T: IndexedResource> ResourceHolder<T> {
    /// Grabs the index of the resource referenced by this holder.
    pub fn get_index(&self) -> usize {
        T::indexed_registry()
            .try_get_index(&self.location)
            .expect("resource should be present if ResourceHolder exists")
    }
}

impl<T: Resource> Deref for ResourceHolder<T> {
    type Target = T;

    fn deref(&self) -> &Self::Target {
        self.reference
    }
}
