[package]
name = "temper-density"
version = "0.1.0"
edition = "2024"

[dependencies]
temper-assets = { workspace = true }
temper-core = { workspace = true }
temper-noise = { workspace = true }
bevy_math = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "density"
harness = false
